version: '3.5'

volumes:
  certificates:

services:
  models-api-ssl-service:
    container_name: models-api-ssl
    image: uowcpc/models-api-ssl:latest
    build:
      context: cert/
      args:
        - DC_DTM_SERVICE_URL=http://172.16.36.177:8080
        - DC_DTM_SERVICE_DOMAIN=dc-dtm-api.pithia.eu
        - WF_DTM_SERVICE_URL=http://172.16.36.177:8081
        - WF_DTM_SERVICE_DOMAIN=wf-dtm-api.pithia.eu
        - SERVICE_EMAIL=kagiald1@westminster.ac.uk
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certificates:/etc/letsencrypt
    healthcheck:
      test: [ 'CMD', '/opt/status.sh' ]
      start_period: 30s
      interval: 1m
      timeout: 5s
    restart: unless-stopped
